WebApplication1/Models/Users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public partial class Users
    {
    }

    public class UsersMetadata
    {
    }
}

WebApplication1/Controllers/BMIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class BMIController : Controller
    {
        // GET: BMI
        public ActionResult Index()
        {
            return View(new BMIData());
        }

        [HttpPost]
        public ActionResult Index(BMIData data)
        {
            if (ModelState.IsValid)
            {
                float m_hh = data.Height / 100;
                float bmi = data.Weight / (m_hh * m_hh);

                string level = "";
                if (bmi < 18.5)
                {
                    level = "太瘦";
                }
                else if (bmi > 18.5 && bmi < 24)
                {
                    level = "適中";
                }
                else if (bmi > 35)
                {
                    level = "太胖";
                }

                data.BMI = bmi;
                data.Level = level;
            }

            return View(data);

        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Test() {

            return View();
        }
        public ActionResult Data()
        {
            ViewData["school"] = "靜宜";
            return View();
        }
        public ActionResult Bag()
        {
            ViewBag.phone = "04-123456789";
            return View();
        }
    }
}

WebApplication1/Views/BMI/Index.cshtml
@model WebApplication1.ViewModel.BMIData
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<form method="post" action="/BMI/Index">
    身高 : @Html.TextBoxFor(f => f.Height) 公分 @ViewBag.HeightError @Html.ValidationMessageFor(f => f.Height)<br /><br />
    體重 : @Html.TextBoxFor(f => f.Weight) 公斤 @ViewBag.WeightError @Html.ValidationMessageFor(f => f.Weight)<br /><br />
    <input type="submit" value="送出" />
</form>
<br />

計算結果： @Model.BMI <br />
等級： @Model.Level

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Bag.cshtml
@{
    ViewBag.Title = "Bag";
}

<h2>Bag</h2>

<p>
    @ViewBag.phone
</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Data.cshtml
@{
    ViewBag.Title = "Data";
}

<h2>Data</h2>

<p>
    @ViewData["school"]
</p>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

@{ 
    string[] fruits = { "蘋果", "香蕉", "荔枝", "鳳梨", "西瓜" };
}

<ol>
@{ 
    foreach (var item in fruits)
    {
        <li>
            @item <br/>
        </li>
    }
}
</ol>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                    <li>@Html.ActionLink("BMI計算", "Index", "BMI")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式  YI-XUAN LIN</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>